spring.application.name=em-project
server.port=9090
# Set up database
spring.datasource.url=jdbc:mysql://localhost:3306/em_system
spring.datasource.username=root
spring.datasource.password=Amaan@123
# Database connector
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# Automatic table creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true